version: '3.5'
services:
  gql-auth:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    networks: 
      - internal
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: softkey
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
  auth-service:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    # command: ./wait-for-it.sh prisma:4466 -- npm run deploy
    command: ./wait-for-it.sh prisma:4466 -t 30 -- npm run dev:up
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/generated/prisma-client
    ports:
      - "5000:4000"
    links: 
      - "gql-auth:prisma"
    depends_on: 
      - gql-auth
    environment: 
      PRISMA_MANAGEMENT_API_SECRET: softkey
      KAFKA_CLUSTER:  kafka:9092
    networks: 
      - internal
      # - bridge
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - '27017:27017'
    networks: 
      - internal
    volumes:
      - mongo:/var/lib/mongo/auth
volumes:
  mongo: ~
networks: 
  internal:
    external: true
    name: internal