version: '3.5'
services:
  # Prisma server
  prisma-server: # <--- change this to avoid conflict
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    networks:
      - internal
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: softkey
        port: 4466
        databases:
          default:
            connector: mongo 
            uri: mongodb://prisma:prisma@service-db # <--- change this to the name of the db image like this => uri: mongodb://prisma:prisma@name
  # Main Service
  auth-service:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    # command: ./wait-for-it.sh prisma:4466 -- npm run deploy #use this for production
    command: ./wait-for-it.sh prisma:4466 -- npm run dev:up  #use this for production
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/generated/prisma-client
    ports:
      - "5000:4000" # <--- change this port mapping if you are running something on port 5000
    links: 
      - "prisma-server:prisma" # <--- change this to avoid conflict and to correspond with the prisma server name like this  "my-prisma-server:prisma"
    depends_on: 
      - prisma-server # <--- change this to avoid conflict and to correspond with the prisma server name like this  "my-prisma-server:prisma"
    environment: 
      PRISMA_MANAGEMENT_API_SECRET: softkey
      KAFKA_CLUSTER: kafka:9092 # <-- kafka-service name as host, if kafka is in the same network else add a host mapping
    networks: 
      - internal
  service-db: # <--- change this to avoid conflict and to correspond with the prisma server name like this  "my-prisma-server:prisma"
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - '27017:27017'
    networks: 
      - internal
    volumes:
      - service-db:/var/lib/mongo/auth
volumes:
  service-db: ~
networks: 
  internal: # <-- create a bridge network
    external: true
    name: internal