version: '3.5'
services:
  # Prisma server
  prisma-server: # <--- change this to avoid conflict
    image: prismagraphql/prisma:1.34
    restart: always
    networks:
      - internal
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: softkey
        port: 4466
        databases:
          default:
            connector: mongo 
            uri: mongodb://prisma:prisma@service-db # <--- change this to the name of the db image like this => uri: mongodb://prisma:prisma@name
  # Main Service
  auth-service: # <--- change this to avoid conflict
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    # command: ./wait-for-it.sh prisma:4466 -- npm run deploy #use this for production
    command: ./wait-for-it.sh prisma:4466 -- npm run dev:up  #use this for production
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/generated/prisma-client
    ports:
      - "5002:4000" # <--- change this port mapping if you are running something on port 5000
    links: 
      - "prisma-server:prisma" # <--- change this  to correspond with the prisma server name like this  "my-prisma-server:prisma"
    depends_on: 
      - prisma-server # <--- change this to correspond with the prisma server name like this  "my-prisma-server"
    environment: 
      PRISMA_MANAGEMENT_API_SECRET: softkey
      KAFKA_CLUSTER: kafka:9092
      SCHEMA_REGISTRY: http://registry:8081
    extra_hosts:  #<--- use this if kafka is not on the same host and docker network
      - "kafka:127.0.0.1"
      - "registry:127.0.0.1"
    networks: 
      - internal
  service-db: # <--- change this to avoid conflict and to correspond with the prisma server name like this  "my-prisma-server:prisma"
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    networks: 
      - internal 
    volumes:
      - service-db:/var/lib/mongo/auth #<---- change this too
volumes:
  service-db: ~ #<---- and change this too
networks: 
  internal: # <-- create a bridge network 
    external: true
    name: internal